---
- name: set acl on httpd log dir
  acl: name=/var/log/httpd entity=logstash etype=user permissions=rx state=present
  when: logstash_shipper == true and logstash_input_httpd == true
#first logrotate w acl support
#Wed Feb 01 2012 Jan Kaluza <jkaluza@redhat.com> 3.7.8-14